### ISSUE TITLE
Authent and users management

### ISSUE THREAD

**Issue by tcccorp** [CIRCL/AIL-framework#223] opened 2018-07-07 11:39 UTC
Hello, hope it is the right place to post this request 

I tested AIL and I love it :)  but it is directly connected to internet . Do you plan ti add a login page and  something to manage users ? Same about the configuration of email server ( when AIL detects a keyword for IE)

Thanks

Serge

**Comment by adulau** [comment] 2018-07-07 11:45
Thank you for the feedback.

It's something we have in the long list of features to be implemented ;-) In the meantime, a reverse proxy with an user-authentication can do the job.

**Comment by mokaddem** [comment] 2018-07-09 06:13
Duplicate of #155

**Closed** 2018-07-15 09:52 UTC
Labels: duplicate, enhancement

**Comment by adulau** [comment] 2019-07-05 13:56
It's now fixed in release v2.0 - d937c03ddbbf371ecc8e3f3525a1d31069a5ecb1

**Comment by tcccorp** [comment] 2019-07-07 15:07
Hello, Thanks for this new version :) 

Serge
