### ISSUE TITLE
Exception on dashboard

### ISSUE THREAD

**Issue by cudeso** [CIRCL/AIL-framework#123] opened 2017-07-08 19:42 UTC
Hi,

On some occasions the Flask webserver returns an exception

192.168.218.1 - - [08/Jul/2017 23:37:38] "GET /_stuff HTTP/1.1" 200 -
192.168.218.1 - - [08/Jul/2017 23:37:39] "GET /_logs HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.218.1', 59155)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

It happens when the startpage of the dashboard is loaded, no user-interaction (during auto refresh).
AIL is the VM image from https://www.circl.lu/services/ail-training-materials/#ail-virtual-machine
Browser is latest Chrome on OSX.
No visual errors in the web page.

kr,

koen

**Comment by mokaddem** [comment] 2017-08-24 14:32
Hi,

I already encountered this error. It is caused by Flask trying send logs data to the dashboard while the socket has been closed (user click on a link, ...). 

However, I don't remember seeing this without user interaction. Perhaps, some kind of disconnection occurs.

Thank you for the feedback.

**Comment by Terrtia** [comment] 2021-04-22 16:21
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.

**Closed by Terrtia** 2021-04-22 16:21 UTC
